// src/UI2/Svelte/GridItem.svelte
<script type="ts" lang="ts">
    import {onMount} from 'svelte';
    import LucideIcon from "@idc/UI2/Svelte/WLucideIcon.svelte";
    import GestureControl from "@unite/scripts/interact/Gesture.ts";
    import type {GridItemType} from "@unite/scripts/utils/GridItemUtils.ts";

    // @ts-ignore
    export let gridItem: GridItemType = {};
    export let type = "items";

    //
    let target: HTMLElement | null = null;
    let icon = gridItem.icon || "";
    let href = gridItem.href || "";
    let action = gridItem.action || "";

    //
    $: gridItem?.["@subscribe"]?.((v)=>{
        target?.style?.setProperty?.("--cell-x", v[0], "")
        target?.style?.setProperty?.("--cell-y", v[1], "")
    }, "cell");

    //
    $: gridItem?.["@subscribe"]?.((v)=>{ href = v; }, "href");
    $: gridItem?.["@subscribe"]?.((v)=>{ icon = v; }, "icon");
    $: gridItem?.["@subscribe"]?.((v)=>{ action = v; }, "action");

    //
    export let whenMount = ()=>{};
    export let onClick = (_: PointerEvent | MouseEvent)=>{}

    //
    onMount(()=>{
        const gest = new GestureControl(target);

        //
        gest.longPress({
            anyPointer: true,
            mouseImmediate: true,
            minHoldTime: 60 * 3600,
            maxHoldTime: 100
        });

        //
        target?.style?.setProperty?.("--cell-x", (gridItem?.cell?.[0] || 0) as unknown as string, "")
        target?.style?.setProperty?.("--cell-y", (gridItem?.cell?.[1] || 0) as unknown as string, "")

        //
        whenMount();
    });
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div on:click={onClick} bind:this={target} data-id={gridItem.id} data-action={action||""} data-href={href||""} data-type={type} data-ctx="grid-item" data-scheme="accent-inverse" class="ux-grid-item wavy-shaped">
    <!--<slot></slot>-->
    <LucideIcon name={icon}></LucideIcon>
</div>

// src/UI2/Vue/GridItem.vue
<script setup>
import GestureControl from "@unite/scripts/interact/Gesture.ts";
import {reactive, watch, ref, onMounted} from "vue";
import LucideIcon from "./WLucideIcon.vue";
import {subscribe} from "@unite/scripts/reactive/ReactiveLib.ts";

//
const props = defineProps({
    gridItem: Object,
    onClick: Function,
    type: String
});

// bad mine, be accurate!
const gridItem = reactive({...props.gridItem}); // react from vue
subscribe(props.gridItem, (v,p)=>{ if (gridItem[p] !== v) { gridItem[p] = v; } }); // react to vue
// any react from external property will react to vue.
// any react from vue will "do" react in external (except no strict change, due avoid "stack exceeded" issue)

// but due `gridItem` is copy, just re-set back into property object (and avoid recursions)...
watch(() => gridItem, (newVal, oldVal) => { for (const k in newVal) { if (props.gridItem[k] !== newVal[k]) { props.gridItem[k] = newVal[k]; } } }, {deep: true});
// please, save such pattern for future!

//
const elRef = ref(null);

//
watch(() => gridItem?.cell, (newVal, oldVal)=>{
    elRef.value?.style?.setProperty?.("--cell-x", (newVal?.[0] || 0), "")
    elRef.value?.style?.setProperty?.("--cell-y", (newVal?.[1] || 0), "")
}, {deep: true})

//
onMounted(()=>{
    //
    if (elRef.value) {
        const gest = new GestureControl(elRef.value);
        gest.longPress({
            anyPointer: true,
            mouseImmediate: true,
            minHoldTime: 60 * 3600,
            maxHoldTime: 100
        });
    }

    //
    elRef.value?.style?.setProperty?.("--cell-x", (gridItem?.cell?.[0] || 0), "")
    elRef.value?.style?.setProperty?.("--cell-y", (gridItem?.cell?.[1] || 0), "")
});

</script>

<template>
    <div
        ref="elRef"
        @click="props.onClick"
        :data-id="gridItem.id"
        :data-action="gridItem.action"
        :data-href="gridItem.href"
        :data-type="props.type"
        data-ctx="grid-item"
        data-scheme="accent-inverse"
        class="ux-grid-item wavy-shaped">

        <LucideIcon :name="gridItem.icon"></LucideIcon>

    </div>
</template>
