// src/App/Vue/ControlCenter.vue
<script setup>
	import { currentLocationHash } from "@unite/svelte/utils/Realtime.ts";
    import {observeBySelector} from "@unite/scripts/dom/Observer.ts"
    import {MOC, MOCElement} from "@unite/scripts/utils/Utils.ts";
    import States from "@unite/scripts/reactive/StateManager.ts";

    //
    import {reactive, watch, ref, onMounted} from "vue";

    //
    import LucideIcon from '@idc/UI2/Vue/WLucideIcon.vue';;

    //
    import Manager from "./Manager.vue";
    import Settings from "./Settings.vue";

    //
    const UIState = States.getState("UIState");

    //
    const props = defineProps({
        appId: {type: String, default: "#control-center"}
    });

    //
    const currentPage = ref("wallpapers");
    const panelOpen = ref(false);

    //
    const panelEl = ref(null);
    const controlEl = ref(null);

    //
    const _LOG_ = (v)=>{
        console.log(v);
        return v;
    }

    //
    UIState?.["@subscribe"]?.((v)=> (currentPage.value = v), "controlCenterPage");
    UIState?.["@subscribe"]?.((v)=> (panelOpen.value = !!v), "controlCenterPanelOpen");

    //
    const tabs = [{
        "page": "settings",
        "icon": "settings",
        "label": "Settings"
    }, {
        "page": "wallpapers",
        "icon": "wallpaper",
        "label": "Wallpapers"
    }];

    //
    observeBySelector(document.body, props.appId, ({addedNodes})=>{
        controlEl.value ||= addedNodes[0];
    });
</script>

<!-- -->
<template>
    <div class="ux-title-label" style="background-color: transparent;">
        <span tabindex="-1" inert :key="currentPage">{{tabs.find(({page})=>(page==currentPage))?.label || ""}}</span>
    </div>

    <div class="ux-content stretch" :id="props.appId.replace('#','')" ref="controlEl" :data-current-page="currentPage">
        <x-scrollbox :data-hidden="!panelOpen" data-instant data-scheme="solid" data-highlight="2" class="ls-panel" ref="panelEl">
            <div v-for="tab in tabs" style="--decor-size: 4rem;" class="ux-block-decor ls-tab-item" data-scheme data-highlight="2" :data-page="tab.page">
                <LucideIcon inert data-place="icon" :name="tab.icon"/>
                <span inert class="tab-label">{{tab.label}}</span>
                <LucideIcon inert data-place="element" name="chevron-right"/>
            </div>
        </x-scrollbox>

        <Settings :data-hidden="currentPage != 'settings'" data-instant></Settings>
        <Manager :data-hidden="currentPage != 'wallpapers'" data-instant></Manager>
    </div>
</template>

// src/App/ControlCenter/ControlCenter.svelte
<script>
	import { currentLocationHash } from "@unite/svelte/utils/Realtime.ts";
    import LucideIcon from '@idc/UI2/Design/WLucideIcon.svelte';
    import Block from '@idc/UI2/Design/Block/Block.svelte';
    
    //
    import {observeBySelector} from "@unite/scripts/dom/Observer.ts"
    import {MOC, MOCElement} from "@unite/scripts/utils/Utils.ts";

    //
    import { writable } from "svelte/store";
    import { fade } from "svelte/transition";

    //
    import Manager from "../Manager/Manager.svelte";
    import Settings from "../Settings/Settings.svelte";
    
    //
    import States from "@unite/scripts/reactive/StateManager.ts";
    const UIState = States.getState("UIState");

    //
    export let appId = "#control-center";

    //
    let currentPage = "wallpapers";
    UIState?.["@subscribe"]?.((v)=> (currentPage = v), "controlCenterPage");

    //
    let panelOpen = false;
    UIState?.["@subscribe"]?.((v)=> (panelOpen = v), "controlCenterPanelOpen");

    //
    let panelEl = null;
    let controlEl = null;
    
    //
    const tabs = [{
        "page": "settings",
        "icon": "settings",
        "label": "Settings"
    }, {
        "page": "wallpapers",
        "icon": "wallpaper",
        "label": "Wallpapers"
    }];

    //
    observeBySelector(document.body, appId, ({addedNodes})=>{
        controlEl ||= addedNodes[0];
    });
</script>

<script context="module">
    import {propsFilter} from "@unite/scripts/utils/Utils.ts";
</script>

<!-- -->
<div class="ux-title-label" style="background-color: transparent;">
    <span tabindex="-1" inert={true}>{tabs.find(({page})=>(page==currentPage))?.label || ""}</span>
</div>

<div class="ux-content stretch" id={appId.replace("#","")} bind:this={controlEl} data-current-page={currentPage}>

    {#if panelOpen}
        <x-scrollbox data-scheme="solid" data-highlight="2" class="ls-panel" bind:this={panelEl} transition:fade={{ key: currentPage, delay: 0, duration: 100 }}>
            {#each tabs as tab}
                <Block style="--decor-size: 4rem;" class="ux-block-decor ls-tab-item" data-scheme data-highlight="2" data-page={tab.page}>
                    <LucideIcon inert={true} data-place="icon" name={tab.icon}/>
                    <span inert={true} class="tab-label">{tab.label}</span>
                    <LucideIcon inert={true} data-place="element" name={"chevron-right"}/>
                </Block>
            {/each}
        </x-scrollbox>
    {/if}
    
    {#if ["settings"].indexOf(currentPage) >= 0}
        <Settings></Settings>
    {/if}
    
    {#if ["wallpapers"].indexOf(currentPage) >= 0}
        <Manager></Manager>
    {/if}
    
</div>

<style type="scss" lang="scss">

</style>
