// src/UI2/Vue/ContextMenu.vue
<script setup>
import Block from "./Block.vue";
import Frame from "./Frame.vue";
import LucideIcon from "./WLucideIcon.vue";

//
const props = defineProps({
    ctxName: String,
    ctxList: Array
});

//
/*export let ctxName = "ctx-menu";
export let ctxList = [{
    icon: "wallpaper",
    name: "Test",
    action: "unknown"
}];*/
</script>

<template>
    <Frame :data-ctx-name={props.ctxName} class="ux-modal-frame ux-context-menu">
        <div v-for="L in props.ctxList" class="ux-block-decor" data-highlight-hover="1" style="--decor-size: 3rem" :data-action={L.action}>
            <LucideIcon :icon={L.icon} data-place="icon"></LucideIcon>
            <span>{{L.name}}</span>
            <div data-place="element"></div>
        </div>
    </Frame>
</template>

// src/UI/contextmenu/ContextMenu.svelte
<script lang="ts" type="ts">
    import Block from "../design/block/Block.svelte";
    import Frame from "../design/frame/Frame.svelte";

    import WLucideIcon from "../design/WLucideIcon.svelte";

    //
    import {writable} from "svelte/store";

    //
    import {zoomOf} from "@unite/scripts/utils/Utils.ts";

    //
    export let ctxName: string = "default";
    export let actionMap: Map<string, Function> = new Map<string, Function>([]);
    export let ctxList = [{
        icon: "wallpaper",
        name: "Test",
        action: "unknown"
    }];
    
    //
    let initiator: HTMLElement | null = null;
    let hasInitiator = writable(!!initiator);
    
    //
    hasInitiator.subscribe((v)=>{
        if (!v) { initiator = null; }
    });
    
    //
    document.addEventListener("contextmenu", (ev)=>{
        const target = ev.target as HTMLElement;
        
        //
        if (target.matches(".ux-context-menu") || target.closest(".ux-context-menu")) {
            ev.stopPropagation();
            ev.preventDefault();
        }
        
        //
        if (target.matches("*[data-ctx=\""+ctxName+"\"]")) {
            ev.stopPropagation();
            ev.preventDefault();
            initiator = target;
            hasInitiator.set(!!initiator);
            
            //
            requestAnimationFrame(()=>{
                const ctxMenu: HTMLElement | null = document.querySelector(".ux-context-menu[data-ctx-name=\""+ctxName+"\"]");
                if (ctxMenu) {
                    ctxMenu.style.setProperty("--click-x", (ev.clientX / zoomOf()) as unknown as string, "");
                    ctxMenu.style.setProperty("--click-y", (ev.clientY / zoomOf()) as unknown as string, "");
                }
            })
        }
        
        //
        if (!(target.matches("*[data-ctx=\""+ctxName+"\"]"))) {
            initiator = null;
            hasInitiator.set(!!initiator);
        }
    });
    
    
    //
    const onClick = (ev)=>{
        const target = ev.target as HTMLElement;
        
        //
        actionMap?.get?.(target.dataset.action as string)?.({
            initiator
        });
        
        //
        initiator = null;
        hasInitiator.set(!!initiator);
    }
    
    
    //
    document.addEventListener("click", (ev)=>{
        const target = ev.target as HTMLElement;
        
        if (!(target.matches(".ux-context-menu[data-ctx-name=\"" + ctxName + "\"]") || target.closest(".ux-context-menu[data-ctx-name=\"" + ctxName + "\"]")) || target.matches("*[data-action]")) {
            requestAnimationFrame(()=>{
                initiator = null;
                hasInitiator.set(!!initiator);
            });
        }
    });

</script>

<Frame focused={hasInitiator} data-ctx-name={ctxName} class="ux-modal-frame ux-context-menu">
    {#each ctxList as L}
        <Block onClick={onClick} class="ux-block-decor ux-default-theme" data-highlight-hover="1" style="--decor-size: 2rem" data-action={L.action}>
            <WLucideIcon name={L.icon} slot="icon"></WLucideIcon>
            <span>{L.name}</span>
            <div slot="element"></div>
        </Block>
    {/each}
</Frame>
