// src/UI2/Vue/DesktopGrid.vue
<script setup>
    import {reactive, watch, ref, onMounted } from "vue";

    //
    import States from "@unite/scripts/reactive/StateManager.ts"
    import { makeReactiveObject } from "@unite/scripts/reactive/ReactiveObject.ts";
    import {observeBySelector, observeBorderBox} from "@unite/scripts/dom/Observer.ts";

    //
    import GridItem from "./GridItem.vue";
    import GridItemLabel from "./GridItemLabel.vue";

    //
    const props = defineProps({
        state: Object,
        actionMap: Object
    });

    // use same pattern...
    const state = reactive({...props.state}); // react from vue
    props.state?.["@subscribe"]?.((v,p)=>{ if (state[p] !== v) { state[p] = v; } }); // react to vue
    watch(() => state, (newVal, oldVal) => { for (const k in newVal) { if (props.state[k] !== newVal[k]) { props.state[k] = newVal[k]; } } }, {deep: true});
    // please, save such pattern for future!

    // read-only, skip ir-reactivity...
    const $settings = States.getState("settings");
    const settings = reactive({...$settings}); $settings?.["@subscribe"]?.((v,p)=>(settings[p] = v));

    //
    const actionMap = props.actionMap || States.getState("actionMap");

    //
    const elRef = ref(null);
    const gpRef = ref(null);
    let current = "main";

    //
    const changeLayout = ()=>{
        elRef.value?.style?.setProperty?.("--columns", settings.columns, "")
        elRef.value?.style?.setProperty?.("--rows", settings.rows, "")
    }

    //
    settings?.["@subscribe"]?.((value, prop)=>{
        changeLayout();
    });

    //
    const onItemClick = (ev)=>{
        const target = ev.target;
        actionMap?.get?.(target.dataset.action)?.({
            initiator: target
        });
    }

    //
    const isItemInList = (id)=>{
        const item = typeof id == "string" ? props.state.items.get(id) : id;
        const ptr = item.pointerId;
        return props.state.lists.get(current)?.has?.(item.id) || (ptr != null && ptr >= 0);
    }

    //
    changeLayout();

    //
    onMounted(()=>{
        if (gpRef.value) {
            States.bindState(elRef.value, props.state, ()=>{})
            observeBorderBox(gpRef.value, (box)=>{
                const idc = 0;

                //
                Array.from(props.state.grids.values()).map((g)=>{
                    g.size = [box.inlineSize, box.blockSize];
                });

                //
                gpRef.value?.style?.setProperty?.(["--grid-w", "--grid-h"][idc], box.inlineSize, "")
                gpRef.value?.style?.setProperty?.(["--grid-h", "--grid-w"][idc], box.blockSize, "")
            })
        }
    });

    //
    const wp = localStorage.getItem("@wallpaper") || "./assets/wallpaper/0.jpg";

    //
    const getItems = (items)=>{
        return Array.from(items.values()).filter((item)=>isItemInList(item));
    }


</script>

<!-- -->
<template>
    <canvas is="w-canvas" :data-src="wp"></canvas>
    <div ref="elRef" data-transparent :data-current-page="current" data-ctx="grid-space" data-scheme="accent-inverse" class="ux-desktop-grid stretch grid-based-box pe-enable">

        <div class="ux-grid-layout ux-grid-page" data-transparent>
            <GridItemLabel v-for="item in getItems(state.items)" v-if="state.items" type="labels" :gridItem="item"></GridItemLabel>
        </div>

        <div ref="gpRef" class="ux-grid-layout ux-grid-page" data-transparent>
            <GridItem v-for="item in getItems(state.items)" v-if="state.items" type="items" :onClick="onItemClick" :gridItem="item"></GridItem>
        </div>
    </div>
</template>

// src/UI2/Svelte/DesktopGrid.svelte
<script lang="ts" type="ts">
    import { onMount } from "svelte";
    import States from "@unite/scripts/reactive/StateManager.ts"
    import { makeReactiveObject } from "@unite/scripts/reactive/ReactiveObject.ts";
    import {observeBySelector, observeBorderBox} from "@unite/scripts/dom/Observer.ts";

    //
    import GridItem from "./GridItem.svelte";
    import GridItemLabel from "./GridItemLabel.svelte";

    //
    export let state = null;
    export let settings = States.getState("settings");
    export let actionMap = States.getState("actionMap");

    //
    let lists = state?.lists;
    let grids = state?.grids;
    let items = state?.items;

    //
    let gridPage = null;
    let target = null;
    let columns = settings?.columns || 4, rows = settings?.rows || 8;
    let current = "main";

    //
    const changeLayout = ()=>{
        target?.style?.setProperty?.("--columns", columns as unknown as string, "")
        target?.style?.setProperty?.("--rows", rows as unknown as string, "")
    }

    //
    settings?.["@subscribe"]?.((value, prop)=>{
        if (prop == "columns") { columns = value; };
        if (prop == "rows") { rows = value; };
        changeLayout();
    });

    //
    const onItemClick = (ev)=>{
        const target = ev.target as HTMLElement;
        actionMap?.get?.(target.dataset.action as string)?.({
            initiator: target
        });
    }

    //
    const isItemInList = (id)=>{
        const ptr = items.get(id).pointerId;
        return lists.get(current).has(id) || (ptr != null && ptr >= 0);
    }

    //
    onMount(()=>{
        //
        States.bindState(target, state, ()=>{
            grids = state?.grids;
            items = state?.items;
            lists = state?.lists;
        }).stateBehave(target, (element, prop, value)=>{
            if (prop == "grids") grids = state?.grids;
            if (prop == "items") items = state?.items;
            if (prop == "lists") lists = state?.lists;
        });

        //
        changeLayout();

        //
        observeBorderBox(gridPage, (box)=>{
            const idc = 0;

            //
            Array.from(grids.values()).map((g)=>{
                g.size = [box.inlineSize, box.blockSize];
            });

            //
            gridPage?.style?.setProperty?.(["--grid-w", "--grid-h"][idc], box.inlineSize as unknown as string, "")
            gridPage?.style?.setProperty?.(["--grid-h", "--grid-w"][idc], box.blockSize as unknown as string, "")
        })
    });

</script>

<!-- -->
<canvas is="w-canvas" data-src={(localStorage.getItem("@wallpaper") || "./assets/wallpaper/0.jpg")}></canvas>

<!-- -->
<div bind:this={target} data-transparent data-current-page={current} data-ctx="grid-space" data-scheme="accent-inverse" class="ux-desktop-grid stretch grid-based-box pe-enable">

    <div bind:this={gridPage} class="ux-grid-layout ux-grid-page" data-transparent>
        <!-- -->
        {#each items.values() as item (item.id)}
            {#if isItemInList(item.id)}
                <GridItemLabel type="labels" gridItem={item}></GridItemLabel>
            {/if}
        {/each}
    </div>

    <div bind:this={gridPage} class="ux-grid-layout ux-grid-page" data-transparent>
        <!-- -->
        {#each items.values() as item (item.id)}
            {#if isItemInList(item.id)}
                <GridItem onClick={onItemClick} type="items" gridItem={item}></GridItem>
            {/if}
        {/each}
    </div>

</div>
