// src/UI2/Vue/Frame.vue
<script setup>
    const FocusSelector = ".ux-modal-frame, .ux-modal, .ux-editor, input, button";
    const DNBSelector = "input[type=\"text\"], .ux-editor, input, button";

    //
    const props = defineProps({ self: Object });
    const elRef = props.self || ref(null);

    //
    document.addEventListener("click", (ev)=>{
        const target: HTMLElement = ev.target;
        const modalFrame = elRef.value;

        //
        if (!(modalFrame == target || target.matches(FocusSelector) || target.closest(FocusSelector)) && !(document?.activeElement?.matches(DNBSelector) || target.matches(DNBSelector) || target.closest(DNBSelector)) || target.matches(".ux-modal-frame button")) {
            if (modalFrame.value) {
                modalFrame.dataset.hidden = true;
            }
        }
    });

</script>

<template>
    <div ref="props.self" data-hidden="true" class="ux-modal-frame" v-bind="$attrs">
        <div class="cut-space">
            <slot></slot>
        </div>
    </div>
</template>

// src/UI2/Svelte/Frame.svelte
<script lang="ts" type="ts">
    import type {Readable, Writable} from "svelte/store";
    import {writable} from "svelte/store";
    import {fade} from "svelte/transition";

    //
    const FocusSelector = ".ux-modal-frame, .ux-modal, .ux-editor, input, button";
    const DNBSelector = "input[type=\"text\"], .ux-editor, input, button";

    //
    let modalFrame: HTMLElement | null = null;
    export let self = null;

    //
    document.addEventListener("click", (ev)=>{
        const target: HTMLElement = ev.target as HTMLElement;

        //
        if (!(modalFrame == target || target.matches(FocusSelector) || target.closest(FocusSelector)) && !(document?.activeElement?.matches(DNBSelector) || target.matches(DNBSelector) || target.closest(DNBSelector)) || target.matches(".ux-modal-frame button")) {
            // @ts-ignore
            //focused?.set?.(false);
            if (modalFrame) {
                modalFrame.dataset.hidden = true;
            }
        }
    });

</script>

<script context="module">
    import {propsFilter} from "@unite/scripts/utils/Utils.ts";
</script>

<div bind:this={self} data-hidden="true" class="ux-modal-frame" transition:fade={{ delay: 0, duration: 100 }} bind:this={modalFrame} {...propsFilter($$props)}>
    <div class="cut-space">
        <slot></slot>
    </div>
</div>
