// src/UI2/Vue/Switch.vue
<script setup>
    import LucideIcon from '@idc/UI2/Vue/WLucideIcon.vue';
    import {reactive, watch, ref, onMounted} from "vue";

    //
    import RangeTouch from 'rangetouch';
    import States from "@unite/scripts/reactive/StateManager.ts";

    //
    const input = ref(null);
    const target = ref(null);
    //const state = ref(null);

    //
    const whenChange = (ev)=>{
        const inp = ev.target;
        (target.value).style.setProperty("--value-mod", (inp.valueAsNumber - inp.min) / (inp.max - inp.min), "");
    }

    //
    onMounted(()=>{
        const inp = input.value;
        //state.value = States.getState(target.value.dataset.state);
        (target.value).style.setProperty("--value-mod", (inp.valueAsNumber - inp.min) / (inp.max - inp.min), "");
    });

</script>

<!-- -->
<template>
    <label ref="target" class="ux-input ux-switch" data-scheme data-highlight="1" v-bind="$attrs">
        <input ref="input" @change="whenChange" @input="whenChange" type="range" min="-1" max="1" step="1"/>
        <div class="fill" data-scheme data-highlight="1"></div>
        <div class="track" data-scheme data-highlight="1"></div>
        <div class="thumb icon-sign" data-scheme data-highlight="1"><LucideIcon name="circle"/></div>
    </label>
</template>

// src/UI/inputs/switch/Switch.svelte
<script>
    import LucideIcon from '@idc/UI/design/WLucideIcon.svelte';
    import {onMount} from 'svelte';
    import {writable} from "svelte/store";
    import RangeTouch from 'rangetouch';

    //
    export let fieldName = "";
    let value = $$props?.value || writable(0);
    let container = null;
    let element = null;

    //
    const _whenChange = (ev)=>{
        const el = ev.target;
        value?.set?.(el.valueAsNumber);
        container.style.setProperty("--value-mod", (el.valueAsNumber - el.min) / (el.max - el.min), "");
    }

    //
    onMount(()=>{
        const el = element;
        container.style.setProperty("--value-mod", (el.valueAsNumber - el.min) / (el.max - el.min), "");
        
        //
        const range = new RangeTouch('input[type="range"]', {  });
    });
</script>

<!-- -->
<script context="module">
    import {propsFilter} from "@unite/scripts/utils/Utils.ts";
</script>

<!-- -->
<label bind:this={container} class="ux-switch" data-scheme data-highlight="1">
    <input 
        on:change={_whenChange} 
        on:input={_whenChange} 
        bind:value={$value} 
        bind:this={element}
        type="range" 
        data-name={fieldName} 
        min={-1} max={1} step={1}
        {...propsFilter($$props)}>
    <div class="fill" data-scheme data-highlight="1"></div>
    <div class="track" data-scheme data-highlight="1"></div>
    <div class="thumb icon-sign" data-scheme data-highlight="1"><LucideIcon name={"circle"}/></div>
</label>
