// src/UI2/Vue/Number.vue
<script setup>
import LucideIcon from '@idc/UI2/Vue/WLucideIcon.vue';
import States from "@unite/scripts/reactive/StateManager.ts";

//
import {reactive, watch, ref, onMounted} from "vue";

//
const input = ref(null);
const target = ref(null);

//
//const state = ref(null);
const props = defineProps({
    min: Number,
    max: Number,
    step: Number
});

//
const whenClickDown = ()=>{
    input.value?.stepDown?.();
    input.value?.dispatchEvent(new Event("input", { bubbles: true, cancelable: true, }))
}

//
const whenClickUp = ()=>{
    input.value?.stepUp?.();
    input.value?.dispatchEvent(new Event("input", { bubbles: true, cancelable: true, }))
}

onMounted(() => {
    //state.value = States.getState(target.dataset.state);
});

</script>

<template>
    <div ref="target" data-scheme="solid" data-highlight="1" class="ux-input number-input round-ns" v-bind="$attrs">
        <button type="button" @click="whenClickDown" class="icon-wrap f-minus" data-scheme="solid" data-highlight="2">
            <LucideIcon inert name="chevron-left"/>
        </button>
        <div class="input-wrap hl-ms">
            <input
                ref="input"
                :min="props.min"
                :max="props.max"
                :step="props.step"
                inert
                type="number"
                inputmode="numeric"
                pattern="\d*"
                virtualkeyboardpolicy="manual"
            />
        </div>
        <button type="button" @click="whenClickUp" class="icon-wrap f-plus" data-scheme="solid" data-highlight="2">
            <LucideIcon inert name="chevron-right"/>
        </button>
    </div>
</template>

// src/UI/inputs/number/Number.svelte
<script>
import LucideIcon from '@idc/UI/design/WLucideIcon.svelte';

//
let value = $$props?.value;
let input = null;

//
$: value = $$props?.value;

//
const onchangeInternal = (ev)=>{
    value?.set(input?.valueAsNumber);
}

</script>

<script context="module">
    import {propsFilter} from "@unite/scripts/utils/Utils.ts";
</script>

<!-- -->
<div data-scheme="solid" data-highlight="1" class="number-input round-ns" {...propsFilter($$props)}>
    <button type="button" on:click={()=>{
        input?.stepDown?.();
        onchangeInternal();
    }} class="icon-wrap f-minus" data-scheme="solid" data-highlight="2">
        <LucideIcon inert={true} name={"chevron-left"}/>
    </button>
    <div class="input-wrap hl-ms">
        <input on:change={onchangeInternal} on:input={onchangeInternal} {...propsFilter($$props)} bind:this={input} inert={true} value={$value} type="number" inputmode="numeric" pattern="\d*" virtualkeyboardpolicy="manual"/>
    </div>
    <button type="button" on:click={()=>{
        input?.stepUp?.();
        onchangeInternal();
    }} class="icon-wrap f-plus" data-scheme="solid" data-highlight="2">
        <LucideIcon inert={true} name={"chevron-right"}/>
    </button>
</div>
