// src/ControlCenter.svelte
<script>
	import { currentLocationHash } from "@unite/svelte/utils/Realtime.ts";
    import LucideIcon from '@unite/svelte/UI/design/WLucideIcon.svelte';
    import Block from '@unite/svelte/UI/design/Block.svelte';
    
    //
    import {observeBySelector} from "@unite/scripts/dom/Observer.ts"
    import {MOC, MOCElement} from "@unite/scripts/utils/Utils.ts";

    //
    import { writable } from "svelte/store";
    import { fade } from "svelte/transition";

    //
    import Manager from "./Manager.svelte";
    import Settings from "./Settings.svelte";
    
    //
    export let appId = "#control-center";
    export let windowManager = null;
    export let currentPage = writable("settings");
    
    //
    windowManager?.addTask?.(appId, {
        icon: "settings",
        label: "Settings",
        detached: false
    });

    //
    let panelEl = null;
    let controlEl = null;
    
    //
    let panelOpen = false;//matchMedia("(width < 9in) or (orientation: portrait)");

    //
    const tabs = [{
        "page": "settings",
        "icon": "settings",
        "label": "Settings"
    }, {
        "page": "wallpapers",
        "icon": "wallpaper",
        "label": "Wallpapers"
    }];

    //
    document.documentElement.addEventListener("click", (ev)=>{
        const {target} = ev;
        
        //
        if (target.matches(appId + " .ls-tab-item")) {
            const _ = target.dataset.page || "";
            if (_ != $currentPage) { currentPage?.set?.(_); };
            
            // unable to switch without hiding
            if (controlEl?.clientWidth <= 96 * 9) {
                panelOpen = false;
            }
        } else 
        
        // just hide panel when clicking to nothing
        if (MOC(target, appId) ? !MOC(target, ".ls-panel") : true) {
            panelOpen = false;
        }
    })

    //
    document.documentElement?.addEventListener?.("ux-menu", (ev)=>{
        if (ev.target == controlEl) { panelOpen = !panelOpen; }
    });

    //
    document.documentElement?.addEventListener?.("ux-back", (ev)=>{
        
    });

    //
    observeBySelector(document.body, appId, ({addedNodes})=>{
        controlEl ||= addedNodes[0];
    });
</script>

<script context="module">
    import {propsFilter} from "@unite/scripts/utils/Utils.ts";
</script>

<!-- -->
<div class="ux-title-label ux-solid-transparent">
    <span tabindex="-1" inert={true}>{tabs.find(({page})=>(page==$currentPage))?.label || ""}</span>
</div>

<div class="ux-content stretch" id={appId.replace("#","")} bind:this={controlEl} data-current-page={$currentPage}>

    {#if panelOpen}
        <x-scrollbox class="ls-panel hl-1" bind:this={panelEl} transition:fade={{ key: $currentPage, delay: 0, duration: 100 }}>
            {#each tabs as tab}
                <Block class="ux-block-decor ux-default-theme hl-2h ls-tab-item cursor-pointer pe-enable" data-page={tab.page}>
                    <LucideIcon inert={true} slot="icon" name={tab.icon}/>
                    <span inert={true} class="tab-label">{tab.label}</span>
                    <LucideIcon inert={true} slot="element" name={"chevron-right"}/>
                </Block>
            {/each}
        </x-scrollbox>
    {/if}
    
    {#if ["settings"].indexOf($currentPage) >= 0}
        <Settings></Settings>
    {/if}
    
    {#if ["wallpapers"].indexOf($currentPage) >= 0}
        <Manager></Manager>
    {/if}
    
</div>

<style type="scss" lang="scss">

</style>

// src/App/Vue/ControlCenter.vue
<script setup>
	import { currentLocationHash } from "@unite/svelte/utils/Realtime.ts";
    import {observeBySelector} from "@unite/scripts/dom/Observer.ts"
    import {MOC, MOCElement} from "@unite/scripts/utils/Utils.ts";
    import States from "@unite/scripts/reactive/StateManager.ts";

    //
    import {reactive, watch, ref, onMounted} from "vue";

    //
    import LucideIcon from '@idc/UI2/Vue/WLucideIcon.vue';;

    //
    import Manager from "./Manager.vue";
    import Settings from "./Settings.vue";

    //
    const UIState = States.getState("UIState");

    //
    const props = defineProps({
        appId: {type: String, default: "#control-center"}
    });

    //
    const currentPage = ref("wallpapers");
    const panelOpen = ref(false);

    //
    const panelEl = ref(null);
    const controlEl = ref(null);

    //
    const _LOG_ = (v)=>{
        console.log(v);
        return v;
    }

    //
    UIState?.["@subscribe"]?.((v)=> (currentPage.value = v), "controlCenterPage");
    UIState?.["@subscribe"]?.((v)=> (panelOpen.value = !!v), "controlCenterPanelOpen");

    //
    const tabs = [{
        "page": "settings",
        "icon": "settings",
        "label": "Settings"
    }, {
        "page": "wallpapers",
        "icon": "wallpaper",
        "label": "Wallpapers"
    }];

    //
    observeBySelector(document.body, props.appId, ({addedNodes})=>{
        controlEl.value ||= addedNodes[0];
    });
</script>

<!-- -->
<template>
    <div class="ux-title-label" style="background-color: transparent;">
        <span tabindex="-1" inert :key="currentPage">{{tabs.find(({page})=>(page==currentPage))?.label || ""}}</span>
    </div>

    <div class="ux-content stretch" :id="props.appId.replace('#','')" ref="controlEl" :data-current-page="currentPage">
        <x-scrollbox :data-hidden="!panelOpen" data-instant data-scheme="solid" data-highlight="2" class="ls-panel" ref="panelEl">
            <div v-for="tab in tabs" style="--decor-size: 4rem;" class="ux-block-decor ls-tab-item" data-scheme data-highlight="2" :data-page="tab.page">
                <LucideIcon inert data-place="icon" :name="tab.icon"/>
                <span inert class="tab-label">{{tab.label}}</span>
                <LucideIcon inert data-place="element" name="chevron-right"/>
            </div>
        </x-scrollbox>

        <Settings :data-hidden="currentPage != 'settings'" data-instant></Settings>
        <Manager :data-hidden="currentPage != 'wallpapers'" data-instant></Manager>
    </div>
</template>
