// src/Settings.svelte
<script>
    import LucideIcon from '@unite/design/WLucideIcon.svelte';
    import Block from '@unite/design/Block.svelte';

    //
    import Checkbox from '@unite/inputs/Checkbox.svelte';
    import Number from '@unite/inputs/Number.svelte';
    import Switch from '@unite/inputs/Switch.svelte';

    //
    import { state, layout, size } from "./GridState.ts";
    import { settings } from "./CurrentState.ts";

    //
    import { onMount } from 'svelte';
    import { writable } from "svelte/store";
    import { fade } from "svelte/transition";

    //
    const columns = writable(settings.columns);
    const rows = writable(settings.rows);
    const scaling = writable(settings.scaling);
    const useZoom = writable(settings.useZoom ?? true);
    const theme = writable(settings.theme);

    //
    $: settings.columns = $columns;
    $: settings.rows = $rows;
    $: settings.scaling = $scaling;
    $: settings.useZoom = $useZoom ?? true;
    $: settings.theme = $theme;

</script>

<!-- -->
<div class="ls-screen" id="settings">

    <div class="ls-nav ux-solid hl-1">

    
        <div class="f-space"></div>
    
        <button class="back-act hl-1 hl-2h">
            <div inert={true} class="icon"><LucideIcon slot="icon" name={"arrow-left"}/></div>
            <div inert={true} class="name">Back</div>
        </button>
    </div>
    <x-scrollbox class="ux-space" transition:fade={{ delay: 0, duration: 100 }}>
        <form data-page class="form-wrap hl-ns" data-name="grid-columns-row">
            <div class="form-description"> Grid Layout Settings: </div>
    
            <Block class="ux-block-decor pe-none">
                <span class="opt-label">Columns:</span>
                <LucideIcon slot="icon" name={"columns-3"}/>
                <Number slot="element" value={columns} min={4} max={6} step={1}></Number>
                <!--<RangeSlider slot="element" bind:values={$columns} min={4} max={6} step={1}></RangeSlider>-->
            </Block>
            <Block class="ux-block-decor pe-none">
                <span class="opt-label">Rows:</span>
                <LucideIcon slot="icon" name={"rows-3"}/>
                <Number slot="element" value={rows} min={8} max={12} step={1}></Number>
                <!--<RangeSlider slot="element" bind:values={$rows} min={8} max={12} step={1}></RangeSlider>-->
            </Block>
        </form>
    
        <form data-page class="form-wrap hl-ns" data-name="grid-columns-row">
            <div class="form-description"> Experimental Display Settings: </div>
        
            <Block class="ux-block-decor pe-none">
                <span class="opt-label">Scaling:</span>
                <LucideIcon slot="icon" name={"scaling"}/>
                <Number slot="element" value={scaling} min={0.5} max={1.5} step={0.125}></Number>
                <!--<RangeSlider slot="element" bind:values={$columns} min={4} max={6} step={1}></RangeSlider>-->
            </Block>
        </form>
    
        <form data-page class="form-wrap hl-ns" data-name="grid-columns-row">
            <div class="form-description"> Experimental Color Scheme: </div>
            
            <Block class="ux-block-decor pe-none">
                <span class="opt-label">Theming:</span>
                <LucideIcon slot="icon" name={"scaling"}/>
                <Switch value={theme} slot="element"></Switch>
            </Block>
        </form>
    </x-scrollbox>

</div>

// src/App/Vue/Settings.vue
<script setup>
    import LucideIcon from '@idc/UI2/Vue/WLucideIcon.vue';

    //
    import Number from '@idc/UI2/Vue/Number.vue';
    import Switch from '@idc/UI2/Vue/Switch.vue';

    //
    import { state, layout, size } from "@idc/State/GridState.ts";
    import { settings } from "@idc/State/CurrentState.ts";

    //
    const props = defineProps({
        stateName: { type: String, default: "settings" },
        ifc: Boolean
    });

    //
    const forms = [
        {
            description: "Grid Layout Settings: ",
            fields: [
                {label: "Columns: ", icon: "columns-3", type: "number", params: [4, 6, 1], name: "columns"}, 
                {label: "Rows: ", icon: "rows-3", type: "number", params: [8, 12, 1], name: "rows"}, 
            ]
        },
        {
            description: "Display Settings: ",
            fields: [
                {label: "Scaling: ", icon: "scaling", type: "number", params: [0.5, 1.5, 0.125], name: "scaling"}, 
                {label: "Theme: ", icon: "sun-moon", type: "switch", params: [-1, 1, 1], name: "theme"}, 
            ]
        }
    ]

</script>

<!-- -->
<template>
    <div class="ls-screen" id="settings" v-bind="$attrs">

        <div class="ls-nav" data-scheme="solid" data-highlight="1">
            <div class="f-space"></div>
            <button class="back-act hl-1 hl-2h">
                <div inert class="icon"><LucideIcon slot="icon" name="arrow-left"/></div>
                <div inert class="name">Back</div>
            </button>
        </div>
        <x-scrollbox class="ux-space" >

            <form v-if="forms" v-for="form in forms" data-page class="form-wrap hl-ns" data-name="grid-columns-row">
                <div class="form-description">{{form.description}}</div>
                <div v-if="form.fields" v-for="field in form.fields" class="ux-block-decor pe-none" style="--decor-size: 4rem;" >
                    <span class="opt-label">{{field.label}}</span>
                    <LucideIcon data-place="icon" :name="field.icon"/>

                    <div data-place="element">
                        <Number v-if="field.type == 'number'"
                            :min="field.params[0]"
                            :max="field.params[1]"
                            :step="field.params[2]"
                            :data-state="props.stateName"
                            :data-name="field.name"
                        ></Number>

                        <Switch v-if="field.type == 'switch'"
                            :data-state="props.stateName"
                            :data-name="field.name"
                        ></Switch>
                    </div>
                </div>
            </form>

        </x-scrollbox>

    </div>
</template>
